"""Format encoders (Axis 1: how bytes are encoded). See formats/AGENTS.md.

An encoder is a callable: (spec: DatasetSpec, rows: list[dict]) -> bytes.
It must be pure: no I/O, no network, no filesystem. Delivery is the
sink's job (ADR-0002). Keep encoders pure and every format works with
every sink for free.
"""

from __future__ import annotations

import csv
import io
import json
import xml.etree.ElementTree as ET
from typing import Any, Callable

from ..spec import DatasetSpec

EncoderFn = Callable[[DatasetSpec, list[dict[str, Any]]], bytes]

_REGISTRY: dict[str, EncoderFn] = {}
_EXTENSIONS: dict[str, str] = {}


def encoder(fmt_id: str, extension: str) -> Callable[[EncoderFn], EncoderFn]:
    def deco(fn: EncoderFn) -> EncoderFn:
        if fmt_id in _REGISTRY:
            raise ValueError(f"format '{fmt_id}' already registered")
        _REGISTRY[fmt_id] = fn
        _EXTENSIONS[fmt_id] = extension
        return fn
    return deco


def get_encoder(fmt_id: str) -> EncoderFn:
    try:
        return _REGISTRY[fmt_id]
    except KeyError:
        raise KeyError(f"unknown format '{fmt_id}'. Registered: {sorted(_REGISTRY)}") from None


def get_extension(fmt_id: str) -> str:
    return _EXTENSIONS[fmt_id]


def list_formats() -> list[str]:
    return sorted(_REGISTRY)


# ── Delimited ────────────────────────────────────────────────────────

def _delimited(spec: DatasetSpec, rows: list[dict], delimiter: str) -> bytes:
    buf = io.StringIO()
    writer = csv.DictWriter(buf, fieldnames=[c.name for c in spec.columns],
                            delimiter=delimiter, lineterminator="\n")
    writer.writeheader()
    for r in rows:
        writer.writerow({k: ("" if v is None else v) for k, v in r.items()})
    return buf.getvalue().encode("utf-8")


@encoder("csv", ".csv")
def to_csv(spec: DatasetSpec, rows: list[dict]) -> bytes:
    return _delimited(spec, rows, spec.output.options.get("delimiter", ","))


@encoder("tsv", ".tsv")
def to_tsv(spec: DatasetSpec, rows: list[dict]) -> bytes:
    return _delimited(spec, rows, "\t")


# ── JSON family ──────────────────────────────────────────────────────

@encoder("json", ".json")
def to_json(spec: DatasetSpec, rows: list[dict]) -> bytes:
    indent = spec.output.options.get("indent", 2)
    return json.dumps(rows, indent=indent, default=str).encode("utf-8")


@encoder("ndjson", ".ndjson")
def to_ndjson(spec: DatasetSpec, rows: list[dict]) -> bytes:
    """One JSON object per line. The streaming-native format: this is what
    the kafka/http sinks will frame into per-record messages in Phase 2."""
    return ("\n".join(json.dumps(r, default=str) for r in rows) + "\n").encode("utf-8")


# ── SQL ──────────────────────────────────────────────────────────────

_SQL_TYPE_MAP = {  # python type -> portable SQL type
    int: "INTEGER",
    float: "REAL",
    bool: "BOOLEAN",
}


def _sql_ident(name: str, dialect: str) -> str:
    if dialect == "tsql":
        return f"[{name}]"
    return '"' + name.replace('"', '""') + '"'


def _sql_literal(v: Any, dialect: str) -> str:
    if v is None:
        return "NULL"
    if isinstance(v, bool):
        if dialect == "tsql":
            return "1" if v else "0"
        return "TRUE" if v else "FALSE"
    if isinstance(v, (int, float)):
        return str(v)
    return "'" + str(v).replace("'", "''") + "'"


@encoder("sql", ".sql")
def to_sql(spec: DatasetSpec, rows: list[dict]) -> bytes:
    """CREATE TABLE + batched INSERTs.

    options: dialect ('postgres'|'sqlite'|'tsql', default 'postgres'),
             batch_size (default 500), create_table (default True).
    """
    opts = spec.output.options
    dialect = opts.get("dialect", "postgres")
    batch = int(opts.get("batch_size", 500))
    table = _sql_ident(spec.name, dialect)
    cols = [c.name for c in spec.columns]
    out: list[str] = [f"-- generated by chaff (seed={spec.seed}, rows={spec.rows})"]

    if opts.get("create_table", True):
        # Infer portable types from the first non-null value per column.
        types = {}
        for c in cols:
            sample = next((r[c] for r in rows if r[c] is not None), "")
            types[c] = _SQL_TYPE_MAP.get(type(sample), "TEXT")
        col_defs = ",\n  ".join(f"{_sql_ident(c, dialect)} {types[c]}" for c in cols)
        out.append(f"CREATE TABLE {table} (\n  {col_defs}\n);")

    col_list = ", ".join(_sql_ident(c, dialect) for c in cols)
    for i in range(0, len(rows), batch):
        values = ",\n".join(
            "(" + ", ".join(_sql_literal(r[c], dialect) for c in cols) + ")"
            for r in rows[i:i + batch]
        )
        out.append(f"INSERT INTO {table} ({col_list}) VALUES\n{values};")

    return ("\n\n".join(out) + "\n").encode("utf-8")


# ── XML ──────────────────────────────────────────────────────────────

@encoder("xml", ".xml")
def to_xml(spec: DatasetSpec, rows: list[dict]) -> bytes:
    """Row/field XML. Column names ride in a `name` attribute rather than
    the element tag, so any column name (spaces, punctuation — office Joe
    types freely) is represented exactly with no tag-sanitizing guesswork.

    options: root_tag (default 'dataset'), row_tag (default 'row').

    <dataset name="...">
      <row><field name="case_id">DEA-1234-ABCDE</field>...</row>
    </dataset>
    """
    opts = spec.output.options
    root = ET.Element(str(opts.get("root_tag", "dataset")), {"name": spec.name})
    row_tag = str(opts.get("row_tag", "row"))
    cols = [c.name for c in spec.columns]
    for r in rows:
        row_el = ET.SubElement(root, row_tag)
        for c in cols:
            field = ET.SubElement(row_el, "field", {"name": c})
            v = r[c]
            if v is not None:
                field.text = str(v)
    ET.indent(root)  # stable, deterministic pretty-print
    return ET.tostring(root, encoding="utf-8", xml_declaration=True)


# ── Heavy formats (optional deps under the `formats-extra` extra) ─────
# Imported for their registration side-effect. Each module registers its
# encoder at import time WITHOUT importing its heavy dep (that import is
# lazy, inside the encoder), so core `import chaff.formats` stays dep-free.
from . import avro, excel, parquet  # noqa: E402,F401
