"""Spreadsheet formula neutralization for the delimited and Excel encoders.

Excel and LibreOffice read a cell whose text begins with ``=``, ``+``, ``-``,
``@``, a tab or a carriage return as a *formula* rather than as data. A
dataset is not usually attacker-controlled, but a chaff spec is shareable —
that is the whole point of the library — so a spec authored by one person and
generated by another is a real path for `=HYPERLINK(...)` or a DDE payload to
reach a spreadsheet that someone trusts.

The obvious remedy (OWASP's: prefix every formula-leading value with an
apostrophe) is wrong here, and measurably so. Across the twelve example
specs, 131 of 52,658 generated string values start with a formula lead, and
every single one is a phone number::

    +1-289-253-5482x18761
    +1-341-672-6998

Prefixing those turns the flagship CRM demo into ``'+1-289-253-5482x18761``.
chaff exists so that someone can open the output and walk into a demo, so a
guard that visibly corrupts the most demo-facing column in the catalogue is
not a safe default; it is a different defect.

So the default rule ("smart") asks a sharper question than "what does this
value start with":

  **Can this value reach outside its own cell?**

``=``, ``@``, tab and carriage return are unambiguous formula leads and are
always neutralized. A leading ``+`` or ``-``, though, can only reach beyond
its own cell through a function call (``NAME(``), a DDE pipe (``|``), a sheet
or workbook reference (``!``), or a UNC path (``\\\\``). Without one of those
it is arithmetic over literals — inert, unable to fetch, execute or exfiltrate
anything — and that is exactly what a phone number is.

The residual is stated plainly rather than hidden: under "smart", a value like
``+1+1`` or ``-A1`` still reaches the spreadsheet as a formula. It can compute
a number or read a neighbouring cell in a file chaff itself generated; it
cannot call out. Anyone who wants no formulas at all, at the cost of the
apostrophes, sets ``formula_guard: "strict"``.
"""

from __future__ import annotations

import re
from typing import Any

#: Characters a spreadsheet treats as beginning a formula.
FORMULA_LEADS = ("=", "+", "-", "@", "\t", "\r")

#: Leads that are unambiguously a formula, whatever follows them.
_ALWAYS = ("=", "@", "\t", "\r")

#: Leads that are only dangerous when the value can reach outside its cell.
_CONDITIONAL = ("+", "-")

#: The four ways a ``+``/``-`` formula can reach beyond its own cell:
#: a function call, a DDE pipe, a sheet/workbook reference, a UNC path.
_REACHES_OUT = re.compile(r"[A-Za-z]\s*\(|[|!]|\\\\")

#: Prefix that makes a spreadsheet read the rest of the cell as text.
QUOTE_PREFIX = "'"

MODES = ("smart", "strict", "off")


def guard_mode(options: dict[str, Any]) -> str:
    """Read and validate ``formula_guard`` from an encoder's options.

    An unrecognized value raises rather than silently falling back to the
    default: a typo'd ``"stict"`` that quietly disabled nothing would be the
    kind of guard that reads as enabled and is not.
    """
    mode = options.get("formula_guard", "smart")
    if mode not in MODES:
        raise ValueError(
            f"formula_guard must be one of {', '.join(MODES)} (got {mode!r})")
    return mode


def is_formula(value: str, mode: str = "smart") -> bool:
    """True when a spreadsheet would read `value` as a formula worth stopping.

    Under "strict", any formula lead counts. Under "smart", a leading ``+`` or
    ``-`` counts only when the value can reach outside its own cell.
    """
    if mode == "off" or not value:
        return False
    lead = value[0]
    if lead in _ALWAYS:
        return True
    if lead in _CONDITIONAL:
        return mode == "strict" or bool(_REACHES_OUT.search(value))
    return False


def neutralize(value: Any, mode: str = "smart") -> Any:
    """Return `value` with a quote prefix if a spreadsheet would evaluate it.

    Only `str` values are considered. Numbers are passed through untouched:
    an int of ``-42`` is a number in every encoder that calls this, and
    quoting it would turn real numeric data into text.
    """
    if isinstance(value, str) and is_formula(value, mode):
        return QUOTE_PREFIX + value
    return value
